### ISSUE TITLE
It seems to be dysfunctional? 

### ISSUE THREAD

**Issue by Aubarino** [GrumpyPirate/Sphaxify#6]
_The following is the CMD window i am having issues with._

If i open it in Admin Mode, it looks for the package in the system32 folder
and Implodes instantly on attempt.

But the following is a "normal" run attempt at this.
```

> sphaxify@1.0.4 makezips F:\Software\Sphaxify-1.2.1
> gulp makeZips

'gulp' is not recognized as an internal or external command,
operable program or batch file.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! sphaxify@1.0.4 makezips: 'gulp makeZips'
npm ERR!
npm ERR! Failed at the sphaxify@1.0.4 makezips script.
npm ERR! This is probably not a problem with npm, There is a likely
additional logging output above.
npm WARN Local package.json exists, but mode_modules missing, did you mean
to install?

npm ERR! A complete log of this run can be found in:
npm ERR!   
C:\Users\REDACTED\AppData\Roaming\npm-cache\_logs\2020-09-13T03_33_16_873Z-debug.log

Complete!

Press any key to continue . . . 
```

**Comment by GrumpyPirate** [comment]
Hello,

You want to avoid running as administrator on Windows/Mac/Linux, the tool has been made with normal privileges in mind.

From that error report it looks to me that you've forgotten to install the depenencies, as it can't find `gulp` (which is the task runner that the app uses).

Have another read through the installation instructions in the README, and make sure you've installed the project dependencies either via the CLI with `npm install`, or by double-clicking one of the installer scripts included with the app.

**Comment by Novajoy67** [comment]
Hi GrumpyPirate,

Sorry to bother you, but I also seem to be having trouble with gulp even though I followed (at least I'm pretty sure I did) the README. I've installed Node JS v14.15.4, unzipped Sphaxify v3.0.0, placed the folders in the source-designs path, and double-clicked the _MakePacks.bat. I keep getting the same error, so I'm most likely (pretty sure) doing something wrong. I see no installer script apart from the _MakePacks.bat, which is How To Use option 1 in the README. Sorry if this ends up being a dumb mistake on my part, haha.
[2021-01-29T04_29_50_294Z-debug.log](https://github.com/GrumpyPirate/Sphaxify/files/5891635/2021-01-29T04_29_50_294Z-debug.log)

**Comment by GrumpyPirate** [comment]
Hi @Novajoy67, no worries friend - I'll see if I can reproduce this on Windows and get back to you. 👍

**Comment by GrumpyPirate** [comment]
I've since had a look into this and have been unable to reproduce the issue - I've successfully run the tool on a Win10 machine running node14/npm6. The only thing I can think of at the moment is that the tool might be having an issue with the directory path containing an `&` (`Mods & Resources`) or something, but it's a wild guess.

I'll continue to see if I can reproduce the problem, but in the meantime, I'm actually working on a standalone desktop GUI app that will avoid having to work with janky .bat/.command files and the command line, something I've never been happy about making users do with sphaxify. I should have an alpha version out soon™️, so it may be worth waiting a bit!

**Comment by Novajoy67** [comment]
It's a strange one, for sure. I've tried a few different things (such as changing the directory path - i.e. one without an "&") and still no luck. Sounds like a cool project, I'll definitely wait patiently for it to drop. Can't wait to try it out!

**Comment by GrumpyPirate** [comment]
@Novajoy67 The new app is called 'Smashpak', and a very _very_ **_very_** early version can be downloaded from here: https://github.com/GrumpyPirate/smashpak/releases.

There will be improvements coming to the UI but it currently does everything Sphaxify does, minus the `resizeables` and `thresholdables` customisation, but those are in progress. The folder structure you need to prepare for your source files is exactly the same, and it'll give you a short guide when you start it up.

I opted to create a new repo (and name) altogether, as the tool isn't really tied to Sphax, or any other resource pack for that matter - it's just a resizer tool at the end of the day.

Give it a try 👍

**Comment by GrumpyPirate** [comment]
Going forward as well, Sphaxify won't be maintained, and development will be focused on Smashpak.
